config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "application#hello"
  root "staticpages#home"
  get "staticpages/help"
  get 'staticpages/about'
  get 'staticpages/login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def hello
		render html: "vikas saini"
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/nav"%>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
  <div class="container-fluid ">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav ">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/staticpages/help">Help</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/staticpages/about">About</a>
        </li>
         <%=link_to "Login",staticpages_login_path ,class: "btn btn-lg btn-outline-warning d-flex flex-row-reverse"%>
      </ul>
    </div>
  </div>
</nav>

app/views/staticpages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample
App</title>
</head>
<body>
<h1>About</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on
Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a>
family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a
href="https://screencasts.railstutorial.org/">screencast
series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p>
</body>
</html>

app/views/staticpages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample
App</title>
</head>
<body>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="https://www.railstutorial.org/help">Rails
Tutorial help
section</a>.
To get help on this sample app, see the
<a href="https://www.railstutorial.org/book"><em>Ruby on
Rails
Tutorial</em> book</a>.
</p>
</body>
</html>

app/views/staticpages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample
App</title>
</head>
<body>
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails
Tutorial</a>
sample application.
</p>
<%= link_to image_tag("img1.jpg",height: "100%",width: "100%")%>
</body>
</html>